#!/usr/bin/env bash

VOICE_DIR=$(dirname "${BASH_SOURCE:-$0}")

cd "$VOICE_DIR/@build"

shopt -s nullglob

find "lexicon" -name "*-lex.json" -type f | while read -r file; do
  if [ -f "$file" ]; then pnpm -s dev "$@" "$file"; fi
done
